# Site settings
title: April Gray
email: grayaprild@gmail.com
github_username: agray5
url: "http://localhost:3000"
baseurl: ""

# Build settings
permalink: 'pretty'
include: ['_pages']
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'package.json', 'gulpfile.js', 'README.md']
gems: ['jekyll-sitemap']

# Style settings
sass:
  sass_dir: '_sass'
  style: 'compressed'

# Markdown settings
markdown: GFM
